# Generated by Django 4.0 on 2022-03-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_codeeditor_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
