# Generated by Django 4.0.3 on 2022-04-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_problem_problem_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='time_space_limit',
            new_name='space_limit',
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
