# Generated by Django 4.0.3 on 2022-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_rename_time_space_limit_problem_space_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='space_limit',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
