# Generated by Django 4.0.3 on 2022-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_alter_problem_space_limit_alter_problem_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='space_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
