# Generated by Django 4.0.3 on 2022-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_alter_problem_space_limit_alter_problem_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_liked',
            field=models.ImageField(default=0, upload_to='', verbose_name='点赞'),
        ),
    ]
