# Generated by Django 4.0.3 on 2022-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_alter_article_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.FileField(default=1, upload_to='problem_judge_data\\'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.FileField(default=10, upload_to='problem_judge_data\\'),
            preserve_default=False,
        ),
    ]
