# Generated by Django 4.0.3 on 2022-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_alter_problem_input_alter_problem_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_thmub',
            field=models.TextField(default=''),
        ),
    ]
