# Generated by Django 4.0.3 on 2022-05-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_article_users_thmub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_thmub',
            field=models.CharField(max_length=255),
        ),
    ]
